name: Assign Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write  # Explicitly grants write permission to manage issues

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Ecosystem Action Add Assignees
        uses: actions-ecosystem/action-add-assignees@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: donmjoseph

          
