name: Assign Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write  # Explicitly grants write permission to manage issues

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: donmjoseph

          
